version: 2
jobs:
  build:
    working_directory: ~/my-docker-app
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: circleci/node:4.8.2
    steps:
      - run:
          name: Env Setup
          command:  |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=my-tsi-app-circleci' >> $BASH_ENV     

      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
  test:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: Test
          command: npm test
  deploy: 
    docker: 
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: 
          name: Build and push Docker image
          command: |
            docker build -t tilakshiva/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push tilakshiva/$IMAGE_NAME:$TAG
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master 
  
