version: 2
jobs:
  build:
    working_directory: ~/my-docker-app
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
  test:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: Test
          command: npm test
  deploy: 
    docker: 
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: 
          name: deploy
          command: curl -H "Content-Type:application/json" --data '{"build":true}' -X POST  $DOCKER_HUB_TRIGGER
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master 
  
